# Version: 3.1
version: '3.1'
services:
  db:
    container_name: Pokedex
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - my-db:/var/lib/postgresql/data
      - ./config:/docker-entrypoint-initdb.d
  backend:
    container_name: API
    image: ghcr.io/baptiste-ferrand/pokemon-back:latest
    restart: always
    ports:
      - ${BACKEND_PORT}:3000
  frontend:
    container_name: FRONT
    image: ghcr.io/baptiste-ferrand/pokemon-front:latest
    restart: always
    ports:
      - "8080:80"

volumes:
  my-db: 
    name: pokemonDB